backend/backend/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    #include friday app's urls in friday/ path
    path('friday/', include('friday.urls'), name='friday')
]

backend/friday/urls.py
from django.urls import path
from . import views

app_name='friday'

urlpatterns =[
    #the sensores values are sent by nodemcu in this way
    path('home/<int:temprature>/<int:humidity>/<int:pir>/<int:ldr>/<str:password>/', views.home_recived_data, name='home_recived_data'),

    #live values are displayed in this url
    path('home/live/', views.Live.as_view(), name='live' ),

    #nodemcu will check this url for status
    path('api/', views.api, name='api' ),

    #these 4 urls are for turing relay on or off
    #region relay
    path('lamp/on/', views.lamp_on, name='lamp_on'),
    path('lamp/off/', views.lamp_off, name='lamp_off'),
    path('relay/on/', views.relay_on, name='relay_on'),
    path('relay/off/', views.relay_off, name='relay_off'),
    #endregion

    #control part of the app will be availabe in this url
    path('control/', views.friday_control, name='control'),
]

backend/friday/models.py
from datetime import date
from django.utils import timezone
from django.db import models

#this part of models defines important varibales to save sensoers value and adds time to it
class HomeSide(models.Model):
    #tempratue and humidity varibales will be filled by DHT11 
    tempratue       =           models.IntegerField         (verbose_name='دمای خانه', null=True, blank=True)
    humidity        =           models.IntegerField         (verbose_name='رطوبت', null=True, blank=True)
    #pir module output is a 0-1 number which can be used as boolean
    pir             =           models.BooleanField         (verbose_name='وضعیت سنسور حرکت',blank=True, null=True)
    #ldr number is somthing between 0 and 1023 whcih comes from analog pin of nodemcu
    ldr             =           models.IntegerField         (verbose_name='میزان نور', blank=True, null=True)
    #django will fill this field every time new values are recived
    date            =           models.DateTimeField        (auto_now=True, verbose_name='تاریخ')


    def __str__(self):
        return str(self.date)


class ServerSide(models.Model):
    #this variable will be used to control lamp or the relay connected to nodemcu
    lamp            =           models.BooleanField         (verbose_name='لامپ', null=True, blank=True)
    #the below variable will show the second relay status
    relay2          =           models.BooleanField         (verbose_name='رله شماره دو', null=True, blank=True)
    #date will be added automaticly when ever new instans are build
    date            =           models.DateTimeField        (auto_now=True, verbose_name='تاریخ')
    # if this variable set to True, after detecting any movemnet by PIR, relay2 will be set to True and someting you define will turn on!
    alert_mode      =           models.BooleanField         (verbose_name='حالت هشدار دهی', blank=True, null=True)
    

    def __str__(self):
        return str(self.date)

backend/friday/views.py
from django.http import Http404, HttpResponse, JsonResponse
from django.shortcuts import redirect, render
from .models import HomeSide, ServerSide
from django.views.generic import ListView


#this variable will be used to athenticate the values
#there is 'password' varibale in nodemcu code for the porpuse, they should be the same
server_password = 'yourpassword'


#this function recives and saves the sensors value
def home_recived_data(request, temprature, humidity, pir, ldr, password):
    #here is the password are compared
    if password==server_password:
        #if password is matched, new object will be created to store new values
        home = HomeSide.objects.create(tempratue=temprature,humidity=humidity, pir=pir, ldr=ldr)
        
        #the last status of relaies in our database is got
        obj = ServerSide.objects.last()
        #if value of home pir and alert mode are both set to True, the below relay will become True
        if home.pir and obj.alert_mode:
            obj.relay2 = True
            obj.save()
        home.save()
        return HttpResponse(status=200)
    else:
        #here is the case of not matching passwords
        return HttpResponse('پسورد نا معتبر')


#all saved sensors value will be shown by this CBV and will be paginated by 200 per page
class Live(ListView):
      model = HomeSide
      paginate_by = 200
      context_object_name = 'results'
      template_name = 'friday.html'
      #results will be sorted by the latest
      ordering = ['-date']


#here is where relaies status are outputed for nodemcu to get
def api(request):
    obj = ServerSide.objects.last()
    lamp = obj.lamp
    relay= obj.relay2
    return JsonResponse({'lamp':lamp, 'relay':relay})


#the 4 below functions are for controling relaies
#region controling
def lamp_on(request):
    if request.user.is_superuser:
        obj = ServerSide.objects.last()
        obj.lamp = True
        obj.save()
        return redirect('friday:control')
    else:
        raise Http404("Not Allowed!")

def lamp_off(request):
    if request.user.is_superuser:
        obj = ServerSide.objects.last()
        obj.lamp = False
        obj.save()
        return redirect('friday:control')
    else:
        raise Http404("Not Awllowed!")


def relay_on(request):
    if request.user.is_superuser:
        obj = ServerSide.objects.last()
        obj.relay2 = True
        obj.save()
        return redirect('friday:control')
    else:
        raise Http404("Not Allowed!")


def relay_off(request):
    if request.user.is_superuser:
        obj = ServerSide.objects.last()
        obj.relay2 = False
        obj.save()
        return redirect('friday:control')
    else:
        Http404("Not Allowed!")
#endregion


#this function is used to show controling page
def friday_control(request):
    if request.user.is_superuser:
        obj = ServerSide.objects.last()
        lamp_status = obj.lamp
        relay_status =obj.relay2
        context={
            'lamp_status':lamp_status,
            'relay_status':relay_status,
        }
        return render(request, 'friday-control.html', context)
    
    else:
        raise Http404("Not Allowed!")

backend/templates/friday-control.html
{% extends 'index.html' %}

{% block title %}
بخش کنترل فرایدی
{% endblock %}


{% block content %}
<div class="container text-center col" style="direction: rtl; margin-top: 2%;">
    {% if request.user.is_superuser %}
    <div class="row">
        {% if lamp_status %}
        <h2 class="col col-sm-3">لامپ: <span class="iconify" data-icon="bx:power-off" style="color: rgb(39, 192, 98); margin: 35px;"></span></h2>
        {% else %}
        <h2 class="col col-sm-3">لامپ: <span class="iconify" data-icon="bx:power-off" style="color: rgb(192, 39, 39); margin: 35px;"></span></h2>
        {% endif %}
        <a class="btn btn-success col-sm-2" href="{% url 'friday:lamp_on' %}" style="border-radius: 15px; margin: 35px;">لامپ
            روشن</a>
        <a class="btn btn-danger col-sm-2" href="{% url 'friday:lamp_off' %}" style="border-radius: 15px; margin: 35px;">لامپ
            خاموش</a>
    </div>

    <div class="row">
        {% if relay_status %}
        <h2 class="col col-sm-3">رله: <span class="iconify" data-icon="bx:power-off" style="color: rgb(39, 192, 98); margin: 35px;"></span></h2>
        {% else %}
        <h2 class="col col-sm-3">رله: <span class="iconify" data-icon="bx:power-off" style="color: rgb(192, 39, 39); margin: 35px;"></span></h2>
        {% endif %}
        <a class="btn btn-success col-sm-2" href="{% url 'friday:relay_on' %}" style="border-radius: 15px; margin: 35px; ">رله
            روشن</a>
        <a class="btn btn-danger col-sm-2" href="{% url 'friday:relay_off' %}" style="border-radius: 15px; margin: 35px">رله خاموش</a>
    </div>
    {% else %}
        <h3 style=" color:rgb(139, 9, 9)">اجازه دسترسی به این بخش را ندارید!</h3>
            {% endif %}
    </div>

    {% endblock %}

backend/templates/friday.html
{% extends 'index.html' %}
{% load jalali_tags %}


{% block title %}
سیستم فرایدی
{% endblock %}


{% block content %}
<style>
    td {
        width: 200px;
    }
</style>

<script src="https://code.jquery.com/jquery-3.4.1.min.js"
    integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>

<div id="posts">
    <div class="container">
        {% if request.user.is_superuser %}
        <table class="table table-striped">
            <thead>
                <tr>
                    <td>
                        #
                    </td>
                    <td>
                        <div class="text" dir="rtl">دمای خانه (C)</div>
                    </td>

                    <td>
                        <div class="text" dir="rtl"> رطوبت (٪)</div>
                    </td>

                    <td>
                        <div class="text">وضعیت سنسور حرکت</div>
                    </td>

                    <td>
                        <div class="text">میزان نور</a></div>
                    </td>

                    <td>
                        <div class="text">تاریخ</a></div>
                    </td>
                </tr>
            </thead>
            <tbody>

                {% for result in results %}
                <tr>
                    <td>
                        {{forloop.counter}}
                    </td>
                    <td>{{result.tempratue}}</td>
                    <td>{{result.humidity}}</td>
                    {% if result.pir %}
                    <td style="color: rgb(141, 3, 3);"><span class="iconify" data-icon="bx:run"></span></td>
                    {% else %}
                    <td style="color:rgb(12, 150, 74)"><span class="iconify" data-icon="bx:lock"></span></td>
                    {% endif %}
                    <td>{{result.ldr}}</td>
                    <td>{{result.date | to_jalali}}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <p style="color:rgb(110, 17, 17); direction: rtl;">اجازه دسترسی به این بخش را ندارید.</p>
        {% endif %}
        
        <div class="pagination">
            <span class="step-links" dir="rtl">
                {% if page_obj.has_previous %}
                    <a href="?page=1">&laquo; آخرین</a>
                    <a href="?page={{ page_obj.previous_page_number }}">قبلی</a>
                {% endif %}
        
                <span class="current">
                    صفحه {{ page_obj.number }} از {{ page_obj.paginator.num_pages }}.
                </span>
        
                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">بعدی</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}">آخرین &raquo;</a>
                {% endif %}
            </span>
        </div>
        
    </div>

    <script src="/static/js/jquery-2.2.4.min.js"></script>
    <script src="/static/js/jquery.waypoints.min.js"></script>
    <script src="/static/js/infinite.min.js"></script>
    <script>
    var infinite = new Waypoint.Infinite({
        element: $('.infinite-container')[0],
        handler: function(direction) {

    },
    offset: 'bottom-in-view',

    onBeforePageLoad: function () {
    $('.spinner-border').show();
    },
    onAfterPageLoad: function () {
    $('.spinner-border').hide();
    }

    });

    </script>

    {% endblock %}

backend/templates/index.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>{% block title %} {% endblock %}</title>
  </head>
  <body>
    {% block content %}

    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="https://code.iconify.design/2/2.2.1/iconify.min.js"></script>
  </body>
</html>